### ISSUE TITLE
build-dist 后服务器怎么部署？

### ISSUE THREAD

**Issue by chenmingzhen** [sheinsight/shineout#1009]
我最近在研究shineout的源码~，我注意到dev-server是dev环境的服务，如果执行buid-dist后打包的指令，是不是将react,prop-types,react-dom等cdn引入，再将打包后的js一同引入到index.html,这里需要服务器上做转发之类的嘛？因为看到dev-server中有重定向的操作ctx.redirect('/cn/index/')，如果方便，可以告诉我发布的流程嘛,万分感激!!🎉🎉

**Comment by EastblueOkay** [comment]
@chenmingzhen 你好呀，新年快乐哟😝
Shineout 的打包产物可以在 build 之后查看根目录下的 pages 目录，里面包括了各个版本的文档和一个 index.html，这个 html 会进行一个地址跳转(完成 dev中ctx.redirect的功能)。
在阅读过程中有其他问题可以随时提问哟，任何的意见和建议也可以和我们反馈呢。
再次祝您牛气冲天🐮

**Comment by chenmingzhen** [comment]
感谢感谢🎉！可以了，我这边是nginx服务器~~ 你们是怎么处理刷新404的问题的，

**Comment by EastblueOkay** [comment]
我们是使用Github Pages部署的文档，静态资源的使用受限。在每个路径下我们都生成了相应的 html 文件来做跳转。
具体的你可以在 gh-pages 分支看到。

**Comment by chenmingzhen** [comment]
可以了！😁 在nginx加个配置就行了， location / {$uri/ $uri.html /index.html last; }，感谢你的帮助，祝你新的一年身体健康工作顺利✌
