### ISSUE TITLE
Tooltip goes past edge of screen

### ISSUE THREAD

**Issue by Malvineous** [sheinsight/shineout#1109]
Hello again!

Is it possible to make the Tooltip stay within the screen boundary?  Here is an example:

https://codesandbox.io/s/amazing-waterfall-s35w6

Here the Tooltip goes off the left and right edge of the page when they are very close to the edge.  Changing the position from `bottom` to `left` doesn't fix the one on the right, because then it gets cut off the top of the screen instead.

Is there a way to set the tooltip as `bottom` but have it move left or right to stay within the page boundary?

Many thanks!

**Comment by EastblueOkay** [comment]
@Malvineous Hello friend!
Our positioning of `Tooltip` is a simple pop-up prompt, There is no support for some complex functions.
Your problem can be solved with `Popover`, It can automatically select the pop-up direction according to the position of the component on the screen.  Here is an example:

https://codesandbox.io/s/sparkling-voice-91g78

**Comment by Malvineous** [comment]
That's perfect, thank you!  I replaced the `<Tooltip/>` with a `<Popover/>` and created my own component to set all the defaults (like the colour and the delay time) so that has completely solved my problem.

Thanks so much for your help!
