### ISSUE TITLE
Feature request - refs for Input

### ISSUE THREAD

**Issue by Malvineous** [sheinsight/shineout#1111]
Hello!

I would like to request a new feature for the `<Input/>` component.  I would like to be able to use `ref=` to get access to the underlying HTML `<input/>` component so that I can focus it via code.

Here is an example of what I am trying to do:

https://codesandbox.io/s/amazing-darwin-ng5ot

When you click on the text to rename it, you have to click a second time to focus the text box before you can start typing.  I would like to be able to have the text box focused automatically so you only have to click once.

I would also like to know when the focus has gone away from the text box, so that clicking outside of it will perform the same action as pressing Enter (so once you type text and click away, it will still perform the rename operation).  Perhaps adding an `onBlur` callback to the `<Input/>` could do this?

I would also like to be able to handle the Escape key to cancel the change (like `onEnterPress` but for the Escape key).  Maybe an `onEscapePress` handler could work?  (although if the `ref` were available I could just use that to add my event handler directly which would be fine too.)

Would this be possible?  It looks like using forwarding refs (docs: [English](https://reactjs.org/docs/forwarding-refs.html) [繁體中文](https://zh-hant.reactjs.org/docs/forwarding-refs.html)) would be a quick fix, however you might be able to come up with a better solution than this.

Please let me know if this feature is something you could add!  Many thanks :smile:

**Comment by Malvineous** [comment]
I just noticed you have #1108 which might be related to this.  I am not sure how it works though - it seems to call the `forwardedRef` function too late for what I need?

**Comment by EastblueOkay** [comment]
@Malvineous Hello, after reviewing your needs, I found that there is no need to get the real input node.

1. The native `autoFocus` property can be used to focus the input, and it will automatically focus every time the input is mounted.
2. For inputing content processing, you can use `onKeyDown`
3. `onBlur` will be called when the focus input is lost

I made changes to your code to see if you can achieve your function:
https://codesandbox.io/s/issue-1111-4omjt

**Comment by EastblueOkay** [comment]
If you really want to get input dom node, you can use `forwardedRef `. it needs to be a function, which will pass the input node out after mount.

```js
<Input forwardedRef={el => this.input = el } />
```

**Comment by Malvineous** [comment]
Thank you once again!  That solved my problem perfectly.  I didn't realise `autoFocus` could be used like that!

Strange, I thought I tried `onBlur` earlier and it didn't work, but it seems to be working fine now, following your example.
