### ISSUE TITLE
Trigger Validation for certain Form Elements in a form

### ISSUE THREAD

**Issue by sachithanandhampalaniswamy** [sheinsight/shineout#1231]
Hey,
We are using Rule object to validate form and certainly we came to situation that validation should be triggered from another method rather than on form submit event for set of controls. Note: the validations has to trigger for certain controls not the whole form.

**Comment by EastblueOkay** [comment]
@sachithanandhampalaniswamy Hello friend, sorry to reply you so late
To achieve the function of verifying the specified form, you can use `Form.Flow`.
Here is the useage demo: https://codesandbox.io/s/validate-needed-2hrkx?file=/App.js
