### ISSUE TITLE
Failed Compile 

### ISSUE THREAD

**Issue by 51tharea** [sheinsight/shineout#128]
```
./node_modules/shineout/lib/DatePicker/Range.js
Module not found: Can't resolve 'core-js/modules/es6.array.sort' in 'E:\Projects\App.Bidding\bidding.http\ClientApp\node_modules\shineout\lib\DatePicker'
```

`{
  "name": "ClientApp",
  "version": "0.4.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.17",
    "@fortawesome/free-brands-svg-icons": "^5.8.1",
    "@fortawesome/free-solid-svg-icons": "^5.8.1",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "axios": "^0.18.0",
    "ckeditor4-react": "^0.1.0",
    "classnames": "^2.2.6",
    "connected-react-router": "^6.3.2",
    "history": "latest",
    "hoist-non-react-statics": "^3.3.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-bootstrap-select": "^0.14.0",
    "react-bootstrap-sweetalert": "^4.4.1",
    "react-cropper": "^1.2.0",
    "react-date-range": "^1.0.0-beta",
    "react-dom": "^16.8.6",
    "react-easy-crop": "^1.10.0",
    "react-fast-compare": "^2.0.4",
    "react-helmet": "^5.2.0",
    "react-helmet-async": "^1.0.2",
    "react-image-lightbox": "^5.1.0",
    "react-maskedinput": "^4.0.1",
    "react-placeholder": "^3.0.2",
    "react-redux": "^7.0.1",
    "react-router-dom": "^5.0.0",
    "react-scripts": "^2.1.8",
    "react-text-mask": "^5.4.3",
    "reactstrap": "^8.0.0",
    "redux": "^4.0.1",
    "redux-modal": "^3.0.1",
    "redux-promise": "^0.6.0",
    "redux-saga": "^1.0.2",
    "redux-saga-modal": "^0.3.0",
    "rimraf": "^2.6.3",
    "shineout": "^1.2.8",
    "styled-components": "^4.2.0",
    "sweetalert2": "^8.8.1"
  },
  "scripts": {
    "start": "rimraf ./build && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "node-sass": "^4.11.0",
    "raw-loader": "^2.0.0",
    "redux-devtools": "^3.5.0",
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6"
  },
  "eslintConfig": {
    "extends": "react-app",
    "plugins": [
      "react-hooks"
    ],
    "rules": {
      "react-hooks/rules-of-hooks": "error"
    }
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
  
}
`

**Comment by nikomal** [comment]
Hi!  thanks  for using shineout

You can install babel-polyfill or core-js in your project to fix this problem.

**Comment by nikomal** [comment]
@51tharea  now, you can also upgrade shineout to 1.2.10  and the problem will be fixed.

**Comment by 51tharea** [comment]
Thx mate, fixed problem.
