### ISSUE TITLE
列表渲染偶尔会第一行之前有一大片空白

### ISSUE THREAD

**Issue by smizel** [sheinsight/shineout#1344]
已经出现过三四次了，但是是偶现
![wecom-temp-80ffc7b816b0f239ac3aeb55a4df10ba](https://user-images.githubusercontent.com/35330167/142375249-d0ad0e44-a59e-44bb-9643-56a9910019ac.png)

**Comment by EastblueOkay** [comment]
请问您的 shineout 版本是多少?
