### ISSUE TITLE
在Group的组件中失去受控

### ISSUE THREAD

**Issue by chenmingzhen** [sheinsight/shineout#1516]
例如Checkbox.Group,设置的value仅仅与defaultValue一样的作用，无法做到受控，看到源码中value最终交给Datum.List处理，Datum中无做受控的处理
[沙盒](https://codesandbox.io/s/crimson-thunder-ld78yt?file=/App.js)

**Comment by leehaoChen** [comment]
@chenmingzhen 你好，目前是半受控的状态， value 与 defaultValue 是有区别的： 更新value 值会触发组件更新而defaultValue不会， 但是仍然允许在value不变的情况下修改组件状态， 如果你要完全受控需要设置disabled属性。
