### ISSUE TITLE
Table 行内单元格内容高度不一致时，垂直居中失效

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#181]
![image](https://user-images.githubusercontent.com/26628346/58072555-a00bfe80-7bd2-11e9-8868-a9309440db86.png)

**Comment by nikomal** [comment]
shineout 的table 里面是和 bootstrap 一致,使用的 vertical-align: 'top'.  如果需要的话, 可以设置 table 的 verticalAlign为 middle 即可.

**Comment by zzyper** [comment]
> shineout 的table 里面是和 bootstrap 一致,使用的 vertical-align: 'top'. 如果需要的话, 可以设置 table 的props verticalAlign="middle" 即可.

done.
