### ISSUE TITLE
Iconfont 本地文件使用，API文档未给出说明

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#183]
![image](https://user-images.githubusercontent.com/26628346/58072681-0bee6700-7bd3-11e9-999c-be898165300e.png)

这样写产生 `ES lint` 报错

**Comment by nikomal** [comment]
因为不同的项目webpack 的配置都不太一样,所以文档中并没有写明,后续会考虑加进去的.

使用本地的 css 时, 推荐通过在 Icon 中不传url 的方式. 自己将所需要的字体样式文件引入到项目中即可.
[https://sheinsight.github.io/shineout/1.3.x/cn/components/Icon#heading-3-Icon-](icon)

**Comment by zzyper** [comment]
> 因为不同的项目webpack 的配置都不太一样,所以文档中并没有写明,后续会考虑加进去的.
> 
> 使用本地的 css 时, 推荐通过在 Icon 中不传url 的方式. 自己将所需要的字体样式文件引入到项目中即可.
> https://sheinsight.github.io/shineout/1.3.x/cn/components/Icon#heading-3-Icon-

ok.
