### ISSUE TITLE
Input 被设为 disabled 时，focus 样式未移除

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#185]
有个场景，表格当前行输入后回车从服务器拿到数据，新增一行自动聚焦，拿到数据的行设置为 `disabled`，结果导致 `input-focus` 那个 `class` 没有移除，已经 `disabled` 的输入框仍然有个外发光。

![image](https://user-images.githubusercontent.com/26628346/58084624-d4d97f00-7bed-11e9-9e7b-04bbc4080af5.png)

![image](https://user-images.githubusercontent.com/26628346/58084733-ff2b3c80-7bed-11e9-9298-136420d16af9.png)

![image](https://user-images.githubusercontent.com/26628346/58084741-02262d00-7bee-11e9-8eed-dd8c9c3c257a.png)

`antd` 的方式是没问题的：

![image](https://user-images.githubusercontent.com/26628346/58084673-e6bb2200-7bed-11e9-9bcb-36273e994506.png)

**Comment by zzyper** [comment]
目前只能遍历 `DOM` 手动移除了。

**Comment by EastblueOkay** [comment]
@zzyper 你好，这个问题在 `1.3.2` 版本被修复，感谢对 `Shineout`支持。
