### ISSUE TITLE
table 列resizeble拖动调整列宽时可能出现异常

### ISSUE THREAD

**Issue by dongbin86** [sheinsight/shineout#1858]
![image](https://user-images.githubusercontent.com/6269809/207257327-9c9d9c0b-7381-4ef7-9e2e-2f56028125b6.png)
![image](https://user-images.githubusercontent.com/6269809/207257412-6c9d0a9d-9c4b-4e41-a239-5bdf642055a8.png)

**Comment by dongbin86** [comment]
handleResize方法的colgroup参数，有可能是个undefined，

**Comment by KMS-Bismarck** [comment]
> handleResize方法的colgroup参数，有可能是个undefined，

👋 你好！

目前我们尝试了部分业务场景暂时未能复现该问题（v1.11.3），请问可以提供一下出现该问题的版本和一个具体可复现该问题的示例或场景吗？十分感谢！

这个报错问题在曾经的某次 bug 修复中有涉及到： https://github.com/sheinsight/shineout/pull/1685

出现该问题的大致原因是 Table 在数据置空情况下进行了列拖拽。由于我们的 Table 不考虑空数据下的排列拖拽行为，因此在后续的版本中，我们禁止了对应的操作。

如果你遇到的问题和上述 bug 修复的问题相似，可以尝试升级一下版本 😄

**Comment by dongbin86** [comment]
就是最新版本。我是用来展示400行数据，拖拽以后，列宽度变化会有延时，体验不是很好，就是表格列宽自动调整的速度跟不上我拖拽的速度，这时候再去拖拽别的列宽，就会出现在这种问题。我临时的结局方案是本地build，检查colgroup，如果是undefined就啥也不干。有没有可以交流的微信群？

**Comment by dongbin86** [comment]
我们的数据是会有空数据的，稀疏的表格

**Comment by dongbin86** [comment]
@KMS-Bismarck cool
