### ISSUE TITLE
1.12.0 版本 utils/uuid.js 在 vite 打包时报错

### ISSUE THREAD

**Issue by CYJB** [sheinsight/shineout#1891]
uuid.js 用到了 crypto，vite 会由于浏览器不支持 crypto 报错 `Module "crypto" has been externalized for browser compatibility and cannot be accessed in client code.`。

相关 vite issue https://github.com/vitejs/vite/issues/9942

uuid 的 crypto 依赖是否应该修改一下？

**Comment by leehaoChen** [comment]
hello 这个问题已经修改 可以升级到 1.12.2 版本
