### ISSUE TITLE
Table 控件指定id属性无效

### ISSUE THREAD

**Issue by dizengrong** [sheinsight/shineout#191]
Table 控件指定id属性无效，Table控件生成的html代码里会忽略掉id属性，name属性也时一样

**Comment by nikomal** [comment]
@dizengrong 首先感谢您使用 shineout
因为 Table 组件在最后渲染的时候会生成很多的 html 元素,并不只是一个 table. 而且在固定表头的情况下还会渲染出两个 table. 所以id 等属性意义不是很大. 如果你需要用过这种方式获取 dom 的话. 可以通过 className 或者在外层的 div 绑定 id.

**Comment by dizengrong** [comment]
@nikomal 非常感觉您的答疑，我的主要的目的是想更新table里的数据，目前看来是不是只有外层div绑定 id，然后在重新render整个Table这个方法了？

**Comment by nikomal** [comment]
更新数据的话,你只需要改变传给 Table 的 data 即可. 还是说您想改变什么其他的属性?

**Comment by dizengrong** [comment]
不好意思哈 我是刚接触react，我要怎么把改变的东西传递到Table 的 data 去？
我的控件里写了这个render方法：
`render() {
    this.get_data_from_json()
    return (
      <div id="div_for_conf_tab" style={{ height: '100%', marginBottom: 40 }}>
        <Table keygen="id" size="small" columns={this.get_columns()} bordered data={tab_origin_datas}></Table>
      </div>
    )
  }`

**Comment by nikomal** [comment]
@dizengrong  解决了就行,感谢使用~
