### ISSUE TITLE
按需加载有问题

### ISSUE THREAD

**Issue by boyrest** [sheinsight/shineout#200]
node_modules/shineout/css/styles/select.css
node_modules/shineout/css/styles/treeSelect.css
出现'so'-导致运行报错。

**Comment by nikomal** [comment]
您好, 方便提供一下具体的报错信息和 webpack 的相关配置信息吗. 不知道遇到的具体问题是啥.

**Comment by boyrest** [comment]
> 您好, 方便提供一下具体的报错信息和 webpack 的相关配置信息吗. 不知道遇到的具体问题是啥.

您好，这边你npm install一下，到node_modules/shineout/css/styles/select.css这个目录下面搜索'so'就可以发现问题了，定义css类名有问题，我分包没法做

**Comment by nikomal** [comment]
@boyrest 感谢您帮我们发现了一个 bug. 我们会在下一个小版本中进行修复. 稍后你可以更新一下 shineout 即可解决.

**Comment by boyrest** [comment]
> @boyrest 感谢您帮我们发现了一个 bug. 我们会在下一个小版本中进行修复. 稍后你可以更新一下 shineout 即可解决.

好的非常感谢

**Comment by boyrest** [comment]
> @boyrest 感谢您帮我们发现了一个 bug. 我们会在下一个小版本中进行修复. 稍后你可以更新一下 shineout 即可解决.

给个小建议，就是input 组件的autoComplete是不是最好默认设置成off?

**Comment by nikomal** [comment]
@boyrest  你可以升级一下 1.3.2 里面解决了 css 里面的'so'问题.

至于 input 的 autoComplete, 因为 shineout 是向下兼容的,所以不方便去修改之前已经定下的默认行为的.有需要的话就要自行设置`autoCompolete="off"`
