### ISSUE TITLE
select下拉框无法调节高度，下拉框未到底的时候就向上显示，感觉很奇怪

### ISSUE THREAD

**Issue by boyrest** [sheinsight/shineout#201]
<img width="1172" alt="屏幕快照 2019-05-29 下午7 49 32" src="https://user-images.githubusercontent.com/11408703/58555179-6890f800-824b-11e9-8912-cb0b864ad130.png">

**Comment by nikomal** [comment]
@boyrest 感谢使用 shineout.

`Select` 的下拉菜单是根据位置自动选择向上还是向下的, 您可以尝试一下略微将 `Select` 组件位置上调一点,看看能否解决这个问题. 如果不能解决的话, 可以提供一下使用`Select`组件的代码, 我们会尝试定位问题并解决的.

**Comment by EastblueOkay** [comment]
@boyrest 感谢对`shineout`的支持 😊
### 1. 下拉菜单显示方向
`Select`下拉菜单向上或向下显示取决于`Select表单在浏览器视口的上半部或下半部`，这是自动的。必要时你可以通过`position`来强制控制显示方向：
```javascript
<Select position="drop-up" {...otherProps} />
<Select position="drop-down" {...otherProps} />
```

### 2. 下拉菜单高度调节
`Select`下拉菜单默认高度最大为`250px`，可以通过`height`来设置它：
```javascript
<Select height={100} {...otherProps} />
```

> `position`和`height`在交互和易用性上不建议暴露，暂时为内部API，但您仍可以在项目中使用。

**Comment by boyrest** [comment]
> @boyrest 感谢对`shineout`的支持 😊
> 
> ### 1. 下拉菜单显示方向
> `Select`下拉菜单向上或向下显示取决于`Select表单在浏览器视口的上半部或下半部`，这是自动的。必要时你可以通过`position`来强制控制显示方向：
> 
> ```js
> <Select position="drop-up" {...otherProps} />
> <Select position="drop-down" {...otherProps} />
> ```
> 
> ### 2. 下拉菜单高度调节
> `Select`下拉菜单默认高度最大为`250px`，可以通过`height`来设置它：
> 
> ```js
> <Select height={100} {...otherProps} />
> ```
> 
> > `position`和`height`在交互和易用性上不建议暴露，暂时为内部API，但您仍可以在项目中使用。

我看了你们的下拉实现，为什么是基于 transform: translate的实现而不是最原始的overflow?

**Comment by EastblueOkay** [comment]
@boyrest 你好
根本原因是因为`Shineout`中所有 `类列表组件` 支持 **懒加载**。譬如在`Select`中你可以看到无论数据有多少，下拉菜单始终只会渲染十条。
`Shineout`是一个高性能的React UI组件库，类似的懒加载你可以在很多地方看到：Table、Dropdown、Casader等。
