### ISSUE TITLE
npm包跟github上的代码有些不同，用了表格，发现表头底部border是2px，github上代码已经更新为1px了，好看点

### ISSUE THREAD

**Issue by theFrontCalf** [sheinsight/shineout#221]

**Comment by nikomal** [comment]
@theFrontCalf 感谢您使用 shineout.

表头底部的 `border`的宽度,是和主题有关系的, 默认的主题是`default`和`bootstrap`一致的,表头底部是 2px 的宽度. 您可以使用`antd`的主题,  该主题下的表头底部是 1px

**Comment by theFrontCalf** [comment]
非常感谢，刚开始使用，没有注意到；
