### ISSUE TITLE
没有折叠面板，配合Antd下拉框显示异常

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#239]
![1561538729668](https://user-images.githubusercontent.com/26628346/60165488-f7d10180-9831-11e9-9904-97021fa3e922.jpg)

**Comment by nikomal** [comment]
@zzyper hello~

1. shineout 是有折叠面板的,  https://sheinsight.github.io/shineout/1.3.x/cn/components/Card#heading-4-collapse, 是 Card 拥有折叠的功能.

2. Select 被遮挡的问题,是因为他的父元素有一个`overflow: hidden`. 如果需要超出的话, 可以给 Select 设置一个`absolute`的`props`即可
