### ISSUE TITLE
需要带 Icon 的按钮

### ISSUE THREAD

**Issue by zzyper** [sheinsight/shineout#240]
如果自己在按钮上加 Icon，会导致按钮loading时，出现一个 loading Icon 和 自己加的，共两个 Icon

**Comment by EastblueOkay** [comment]
@zzyper 你好

由于Shineout Icon的特殊设计，Button 并没有类似指定 iconname 的功能，而是需要开发者以 children 的方式将 Icon 传入 Button。
如果需要让 Shineout 识别传入的 children 是一个 icon，可以为您的组件设置 **isShineoutIcon**：
```javascript
function MyIcon() {
    return <span />
}
MyIcon.isShineoutIcon = true
```
