### ISSUE TITLE
这个运行bootstrap4吗？

### ISSUE THREAD

**Issue by zhangqhzz** [sheinsight/shineout#28]
因为系统使用coreUI作为框架，table等想用你这个，而coreUI是使用bootstrap4的，之前有用你的reactui

**Comment by Lobos** [comment]
默认的主题是在视觉上和bootstrap是比较接近的，但是稍微有一点不一样，因为Shineout用了less。Table 应该是可以用的，因为样式不是很多，自己覆盖也比较方便
