### ISSUE TITLE
大佬~能否加一点一点注释。。。

### ISSUE THREAD

**Issue by InitialCC** [sheinsight/shineout#3]
slider 组件源码不是太容易看懂，小弟也在学习当中，能否在关键部分写一点注释。。。

**Comment by Lobos** [comment]
Slider 的设计和正常的思维有一点区别，正常情况下应该，底色灰色层，值使用蓝色层。但是在范围选择的时候就不能复用值选择的组件了。所以 Slider组件底色使用了蓝色，值使用灰色的层，第一个值是100%-value[0]，如果是范围选择，第二个值是 value[1]。这样就可以复用值选择的组件（Slider.js）。
