### ISSUE TITLE
DatePicker如何设置中文

### ISSUE THREAD

**Issue by LumiereXyloto** [sheinsight/shineout#309]
DatePicker默认是英文,如何设置中文呀,试了一试引入shineout/lib/locale/zh-CN没有作用

**Comment by nikomal** [comment]
@LumiereXyloto 欢迎使用 shineout.

我们是在 shineout 里面提供了一下 `setLocale` 的方法去修改我们的语言的. 你只需要这样设置即可: 
```
import { setLocale } from 'shineout'
setLocale('zh-CN')
```

或者查看这里的文档按照需求进行修改  [i18n](https://shine.wiki/1.4.x/cn/components/GetStart#heading-2-I18N)

**Comment by Lobos** [comment]
有个api设置中文的
```
import { setLocale } from 'shineout'
setLocale('zh-CN')
```
