### ISSUE TITLE
Datetime Picker range  end datetime classname

### ISSUE THREAD

**Issue by 51tharea** [sheinsight/shineout#330]
Range function end day position className doesn't set   "so-datepicker-hover-end".

version: 1.4.x

bug :
![image](https://user-images.githubusercontent.com/644199/64616436-3dd74380-d3e5-11e9-89cd-ba3100fba7d5.png)

true :
![image](https://user-images.githubusercontent.com/644199/64616498-5e070280-d3e5-11e9-92bb-096f09483f0a.png)

**Comment by DanielchenN** [comment]
hey, version 1.4.1 has been released! This version not only fixed this bug, but also added new feature which theme can be customized.  u can have a try XD;

**Comment by 51tharea** [comment]
Great!.
Mate, the "DateTimePicker" Range property is the same month in the new version. For example, the first date month, last date month: September | September. The old version was different months.

**Comment by DanielchenN** [comment]
Sorry for confusing you. 
We got some user feedbacks about the complexity in using the Range property of Datepicker. So we  made some changes. Separating the StartDate(in the left) and EndDate(in the right), which brings about the same month on both sides.

**Comment by 51tharea** [comment]
I understand. 
Is it possible to add the old option as an option to be offered as an alternative?

**Comment by DanielchenN** [comment]
In this version, it is hard to do that. |
We will add a props to control that in next version.

**Comment by nikomal** [comment]
in 1.4.2, you can use `defaultRangeMonth` to set  default month of  start  and end

**Comment by 51tharea** [comment]
You are awsome team, thx mate...

**Comment by nikomal** [comment]
@51tharea 😁thx!
