### ISSUE TITLE
<Image/> "lazy" not working in Modal

### ISSUE THREAD

**Issue by hong-chan** [sheinsight/shineout#335]
When using lazy={true} of Image in a Modal, images would not load even when it become visible.

Demo:
https://codesandbox.io/embed/sleepy-dijkstra-pd9q9

**Comment by nikomal** [comment]
in 1.4.2, using  `container`  can let Image lazy in modal or other div which has `overflow: scroll`, see [docs](https://shine.wiki/1.4.x/cn/components/Image#heading-09-lazy)
