### ISSUE TITLE
table rowSpan 合并问题

### ISSUE THREAD

**Issue by han88829** [sheinsight/shineout#349]
根据函数返回的结果（bool）判断是否合并行，a、b为相邻的两行数据。

我想咨询下根据索引index进行合并，怎么进行，比如
` index>=0 && index<=2`
我试了下，如果只是相邻两行对比数据，不够灵活

**Comment by nikomal** [comment]
@han88829  你可以试着这样写

`rowSpan: (a, b) => data.indexOf(a) >= 0 && data.indexOf(b) <= 2`

只需要知道前后两行需不需要合并即可, 你可以看看这样是不是你所要的效果. [合并行示例](https://codesandbox.io/s/relaxed-hooks-zu0wo)
