### ISSUE TITLE
Table组件显示树状数据时， 如果数据量大， 后面的行收缩展开时会出现空白

### ISSUE THREAD

**Issue by xcjiangpeng** [sheinsight/shineout#351]
1万条一级节点， 加上7万条二级节点
![image](https://user-images.githubusercontent.com/13601398/65303761-7b8c5700-dbb1-11e9-9488-348bf8d33bde.png)
在几千行的位置点展开
![image](https://user-images.githubusercontent.com/13601398/65303857-bc846b80-dbb1-11e9-8595-b628ef07d641.png)
收缩的时候， 整个表格就变成空白了， 鼠标再滚动一下， 才会刷新出数据

**Comment by EastblueOkay** [comment]
@xcjiangpeng 您好，请提供一下你的 shineout 版本号？

**Comment by xcjiangpeng** [comment]
"shineout": "^1.4.1",

**Comment by EastblueOkay** [comment]
该问题已经在新版本中修复
