### ISSUE TITLE
树形表格显示展开收起图标不可控

### ISSUE THREAD

**Issue by chenguozhu11** [sheinsight/shineout#359]
实现不了动态加载子数据，可参考antd，列如：子数据字段名：children，当children为[]空数组时显示图标，当children为null、undefined。等空值时不显示图标

**Comment by chenguozhu11** [comment]
将Td.js中59行:(data[treeColumnsName].length === 0)判断条件去除

**Comment by nikomal** [comment]
@chenguozhu11 感谢你的提议, 不过由于我们保证过会一直向下兼容, 所以我们会提供一个新的 `props`去让`children`为空数组的时候展示可展开图标.会在下个版本增加这个功能.感谢反馈~🎉

**Comment by chenguozhu11** [comment]
下个版本将在什么时候进行发布呢？有大概的时间吗？目前表格提供的api比较少，希望持续向下兼容，功能越来越强

**Comment by nikomal** [comment]
预估是在国庆之后会发布新的一版, 届时可以升级体验

**Comment by nikomal** [comment]
1.4.2 已发布, 可以给`Table` 设置 `treeEmptyExpand={true}`, 能够让 children 为空数组的时候依然展示按钮, 可以在 `onTreeExpand` 事件中改变`data` 去实现动态添加数据
