### ISSUE TITLE
Table 性能问题

### ISSUE THREAD

**Issue by liugenpeng** [sheinsight/shineout#368]
SeperateTable.js
----
这里，如果pageSize 较大的话，性能很差，建议优化一下：

resetWidth(left = this.lastResetLeft || 0, right = this.lastResetRight || 0) {
    this.lastResetLeft = left
    this.lastResetRight = right
    setTranslate(this.tbody, `-${left}px`, `-${this.lastScrollTop}px`)
    setTranslate(this.thead, `-${left}px`, '0')
    ;[this.thead, this.tbody].forEach(el => {
      ;[].forEach.call(el.parentNode.querySelectorAll('td, th'), cell => {
        if (cell.classList.contains(tableClass(CLASS_FIXED_LEFT))) {
          setTranslate(cell, `${left}px`, '0')
        } else if (cell.classList.contains(tableClass(CLASS_FIXED_RIGHT))) {
          setTranslate(cell, `-${right}px`, '0')
        } else if (cell.style.transform) {
          setTranslate(cell, '0', '0')
        }
      })
    })
  }

**Comment by nikomal** [comment]
@liugenpeng 你好, 你指的是`[].forEach.call(el.parentNode.querySelectorAll('td, th'), cell => {`这一段代码吗? 因为我们`table` 在渲染的时候使用了懒加载的方式, 一次默认只会渲染20 条,  所以即使是`pageSize`很大的情况,  `querySelectorAll` 的长度一样的最多是 20, 这里的遍历也不会什么性能的问题.

**Comment by liugenpeng** [comment]
@nikomal  可以考虑优化一下 不启动懒加载的场景下大数据量的问题吗

**Comment by liugenpeng** [comment]
不止20个吧

**Comment by nikomal** [comment]
对于大数据量来说, 懒加载就是一种优化方式, 而且几乎是最好的, 因为如果真的要在页面中渲染出成百上千个 tr 的话, 滚动或者全选都是要直接操作大量节点的, 那样的话就会肯定会卡顿的.

在`SeperateTable.js`中,  传给 tbody 的数据都是已经被截取过的, 默认的长度就是`rowInView`

```
<Tbody
   ...
   data={data.slice(currentIndex, currentIndex + rowsInView)}
   ...
/>

**Comment by liugenpeng** [comment]
@nikomal 理解你的说法，懒加载(或者虚拟渲染)对于大数据量来说 基本上也是通用的解决方案。我这里有一些场景可能无法使用懒加载。

对于表格的性能来说，有两个点。
1）是否考虑过使用原生滚动的方式优化大数据量的性能
2）对于不使用懒加载的场景，是否有规划去做优化。如果不启用懒加载 能够支持较大数据的体验，是不是更好一些，毕竟也不能只用懒加载一种方式

**Comment by nikomal** [comment]
@liugenpeng 能提供一下你所遇到的不能使用懒加载时候的真实场景吗? 然后性能问题主要是你在滚动的发生的吗?

**Comment by liugenpeng** [comment]
@nikomal 是的，目前只在滚动的时候比较卡，场景就是系统的用户习惯使用 浏览器的搜索功能
