### ISSUE TITLE
Form里Input会改变绑定field的类型

### ISSUE THREAD

**Issue by wanghengwei** [sheinsight/shineout#398]
如果field是number类型，绑定到它的Input就算设置type为number，一旦修改后，值就变成了string。

用Input.Number倒是没这个问题，但是右边有增减箭头不能去掉

**Comment by nikomal** [comment]
@wanghengwei  是因为为了和浏览器的行为保持一致, 所以`Input`的值传出来之后都会变成`string`, 

`Input.Number`是为了对数字的操作方便的 所以才会有增减的箭头. 如果你一定一定想要去掉的话,可以通过样式的方式进行覆盖(虽然不太建议).

**Comment by leehaoChen** [comment]
@wanghengwei  你好新版本的Input.Number 支持 hideArrow 来隐藏箭头
