### ISSUE TITLE
table固定表头问题

### ISSUE THREAD

**Issue by chenguozhu11** [sheinsight/shineout#415]
table固定表头之后滚动懒加载时，表头和表格数据之前出现较大空隙

**Comment by EastblueOkay** [comment]
@chenguozhu11 您好，可否提供详细的使用方法和错误描述，或直接在此 [codesandbox](https://codesandbox.io/s/37pcf) 代码基础上复现您的问题？

**Comment by chenguozhu11** [comment]
问题原因已找到，未设置表格高度
