### ISSUE TITLE
babel老版本问题

### ISSUE THREAD

**Issue by chenguozhu11** [sheinsight/shineout#417]
使用了@babel/runtime,使用babel7一下就无法启动

**Comment by chenguozhu11** [comment]
与react-scripts@2.x以下使用的babel-runtime冲突

**Comment by nikomal** [comment]
@chenguozhu11 你好, 是否是由于我们项目中的`dependencies`里含有`@babel/runtime'. 感谢提醒, 由于之前移除一些配置的时候未删除完整, 现已将其删除.  👏
