### ISSUE TITLE
webpack 引入问题

### ISSUE THREAD

**Issue by zmh7057** [sheinsight/shineout#453]
直接 npm install 后还需要做什么 webpack 配置 ? 你文档中的配置都是过了，还是有问题哇？

如下，单纯引入，并没有做webpack 的配置

```bash
./node_modules/shineout/lib/styles/spin/chasing-dots.less 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../variables.less';
| 
| @chasing-dots-prefix: ~'@{so-prefix}-chasing-dots';
```

**Comment by nikomal** [comment]
@zmh7057 hello. 我们的样式代码是使用的 less 进行编写, 在文档中有写的
![image](https://user-images.githubusercontent.com/18556302/70404771-0aed2c00-1a76-11ea-86d6-c4c2422c0722.png).
可具体查看这里[webpack引入](https://shine.wiki/1.4.x/cn/components/GetStart#heading-3-webpack)

**Comment by zmh7057** [comment]
@nikomal 已经OK了，感谢 🙏！！。再问一个根table 相关的，如果我只想固定 checkbox ，其他列可进行左右滚动，这个怎么处理？

**Comment by EastblueOkay** [comment]
@zmh7057 你好，你可以在 Table 的 columns 中显式的写一个 type=checkbox 列，然后像固定普通列一样来使用。具体可以查看这个例子：https://codesandbox.io/s/nervous-cdn-zzghr
```javascript
const columns = [{ type: 'checkbox', fixed: 'left' }, ...otherColumns],
```

**Comment by zmh7057** [comment]
@EastblueOkay  ok，感谢
