### ISSUE TITLE
集成shineout后包warning：Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

### ISSUE THREAD

**Issue by ljmkimqx** [sheinsight/shineout#47]
`
./node_modules/shineout/lib/styles/normalize.less (./node_modules/css-loader??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./node_modules/shineout/lib/styles/normalize.less)
Warning

(121:3) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
`

环境：
react 16.8.1
shineout  1.2.4
less: 3.9.0
less-loader: 4.1.0

**Comment by Lobos** [comment]
应该是 autoprefixer 报的(https://github.com/postcss/autoprefixer/issues/1179)，下个版本会移除掉 text-decoration-skip: ink
