### ISSUE TITLE
Image.Upload

### ISSUE THREAD

**Issue by can-acar** [sheinsight/shineout#485]
Hey mate , 
How can I show a image preview in the browser without uploading the image file to the any server?
My opinion; If any action URL is set to the property shall be upload processed.

```
  const readFile = async (file) => {
        return new Promise(resolve => {
            const reader = new FileReader();
            reader.addEventListener('load',  () => resolve(reader.result), false );
            reader.readAsDataURL(file)
        })
    };

 const onChangeImage = async (e) => {
        if (e.target.files && e.target.files.length > 0) {
            const imageData = await readFile(e.target.files[0]); // blob image data
            upload({
               action:"//upload-url.con",
                imageData,
            })
        }
    };

<Upload.Image
drop
accept="image/*"
name="file"
onChange={onChangeImage}
/>


```

**Comment by nikomal** [comment]
hello, if you want to show preview without upload, you can create virtual request, process the file in request. see this demo [demo](https://codesandbox.io/s/autumn-smoke-65mzq)

**Comment by Malvineous** [comment]
@nikomal Would it be possible to add your example to the documentation?  I wanted to do this too and was going to open another issue, but found this one which solved my problem.  It would be great to have it in the docs as an example of how to access file data on the client without sending it to a server.

**Comment by EastblueOkay** [comment]
@Malvineous We will add this example in the next version of the document 😁

**Comment by EastblueOkay** [comment]
@Malvineous We have added this usage in the latest example sources  #1071
The official version to be released soon, it will be able to be viewed through document site

**Comment by Malvineous** [comment]
Perfect, thanks so much!  I see your example is a bit different to the one posted previously so I'll definitely be referring to it when the new version comes out!

**Comment by EastblueOkay** [comment]
@Malvineous Hi, You can view the latest examples through this address
https://shine.wiki/1.6.x/en/components/Upload#heading-08-request-a

**Comment by Malvineous** [comment]
Thank you for this!  I have updated my code to use the new method and it works very well, especially with multiple files.
