### ISSUE TITLE
image 图片样式问题

### ISSUE THREAD

**Issue by mdddj** [sheinsight/shineout#513]
不设置高度会多出一部分

**Comment by mdddj** [comment]
![image](https://user-images.githubusercontent.com/29020213/73440055-99ea3680-438b-11ea-92b6-5d290cd534b4.png)

**Comment by EastblueOkay** [comment]
@mdddj 你好，Image组件在使用时需要指定尺寸。
目前内置了 4 种适应容器的方式，填充、居中、原图、拉伸，详细可查看[示例](https://shine.wiki/1.4.x/cn/components/Image#heading-03-fit)
建议使用填充方式：`fit="fill"`，在保证长宽比的同时在区块内展示图片。
