### ISSUE TITLE
针对Ts的table没有onScroll属性吗

### ISSUE THREAD

**Issue by supconlc** [sheinsight/shineout#529]
针对Ts的table没有onScroll属性吗

**Comment by EastblueOkay** [comment]
@supconlc 你好，感谢你的提醒。
目前 shineout 的 ts 声明文件是使用工具生成的，由于 hoc 的原因某些组件的属性可能不全，之后我们会继续优化这些声明文件。

**Comment by EastblueOkay** [comment]
@supconlc 你好，我们在新版本中已经完善了 ts 的支持，可以升级后体验
