### ISSUE TITLE
如何修改组件主题色

### ISSUE THREAD

**Issue by LiuSandy** [sheinsight/shineout#653]
在ant pro 项目中，引入了shineout 组件库，但是主题色是默认的蓝色，我想修改主题色，怎么修改？

**Comment by EastblueOkay** [comment]
@LiuSandy 您好，shineout的官方文档支持在线主题编辑功能，你可以通过点击网站右上角的”色块“展开主题编辑面板，在编辑完成后点击”导出“按钮。将导出的脚本复制到项目中来应用主题。

同时shineout也提供了API来快捷设置主题属性值，如修改主题色：
```javascript
import { utils } from 'shineout'
utils.cssAccessors.color.primary = 'red'
```
