### ISSUE TITLE
大佬，如何自定义列的颜色？

### ISSUE THREAD

**Issue by ab2976818** [sheinsight/shineout#859]
使用render可以实现定义单元格的颜色，我重写了样式，可以撑开单元格，但是当该单元格没有值时，便是默认颜色，希望增加类似ant-design里可以return cell样式的功能，改变多个列的颜色

**Comment by lsky-walt** [comment]
嗯额 🤔，自定义列样式吗？

你可以在 `Columns` 的对应列添加 `className` 属性，就可自定义该列所有单元格的样式。👏
