### ISSUE TITLE
❗❗ Carousel 实现bug

### ISSUE THREAD

**Issue by chenmingzhen** [sheinsight/shineout#868]
组件 Carousel index.js 中
由于继承于PureComponent  没有在componentDidMount中执行super.componentDidMount()，$isMounted为undefined ，导致moveTo中的this.setState({ pre: current, current: next, direction })不生效 ，进而轮播图不能轮播

**Comment by EastblueOkay** [comment]
@chenmingzhen 
你好，setState中的判断条件是`false`，`undefined`的话会正常执行的。
这个共用Component的目的是保证在组件被卸载之后无法使用`setState`和`forceUpdate`呢。
非常感谢呢🌺

**Comment by chenmingzhen** [comment]
@EastblueOkay
👌👍理解了
