### ISSUE TITLE
好牛批的控件库，沙发

### ISSUE THREAD

**Issue by markz-demo** [sheinsight/shineout#87]
控件都是自己写的吗？写了多长时间啊？
我最新在写Tree控件，网上找到了这个控件库，对于Tree各层之间状态事件管理很纠结，不知道该怎么管理好。
原先我考虑了context，用来管理控件公共变量状态事件，各层之间就靠props传递，传来传去自己都搞蒙了。
看了兄弟的源码，用的是一个Datum类对象来管理，存储状态和事件，然后通过props传入各层，逻辑都写在类里了，外部只需要管理自己组件的状态和dom操作等，看起来很方便。这么设计有什么好处吗？大数据情况怎么样？
还有看源码，发现各组件传递props很暴力，多是整个props（或者other）传入，这样传入很多（或者对象很大，比如Datum），会不会有什么影响啊？小弟初学React时间不长，求大神指教。谢谢！

**Comment by Lobos** [comment]
Datum类是一个注入，反转控制组件状态的。因为传递过程中 datum 是不变的，在做子组件的 scu 时，才能达到比较高的性能。如果传入一个value，数组或者对象，因为外层渲染需要这个value是immutable的，所以更新数据时需要创建新的数组或对象向下传递。而子组件因为接受了这个新的对象，导致scu失败，必须渲染。
另外，Tree 和 Form 都有大量比较复杂的逻辑，在 View 层处理，会导致 View 组件过于复杂，统一在 Datum 这个类里处理可以降低一部分复杂度。
