### ISSUE TITLE
Tabel组件多列排序

### ISSUE THREAD

**Issue by pengzhifang** [sheinsight/shineout#883]
请问在Table组件中可否支持多列同时排序，谢谢！

**Comment by lsky-walt** [comment]
@pengzhifang Hello，[Table是支持多列排序的✌️](https://shine.wiki/1.6.x/cn/components/Table#heading-10-sort-weight)

**Comment by pengzhifang** [comment]
但是我的日期列和名称列同时排序，日期列不生效

**Comment by lsky-walt** [comment]
@pengzhifang Hi，`日期列和名称列同时排序，日期列不生效`，是因为排序的**权重**问题，多列排序时，会根据 `Column` 里`sorter`字段的`weight`来确定优先级。[👉Table多列排序](https://shine.wiki/1.6.x/cn/components/Table#heading-10-sort-weight)

**Comment by pengzhifang** [comment]
好的，多谢，是我自己的日期排序规则有问题，已经解决，感谢
