### ISSUE TITLE
表格滚动列表下半部分变白，数据不显示

### ISSUE THREAD

**Issue by pengzhifang** [sheinsight/shineout#895]
你好，我的表格数据中包含详情按钮，当我点击触发详情按钮操作时，表格数据会出现展示不全的情况，通过控制台检查发现是滚动内容区域高度不够，我猜测与数据懒加载有关系，不知道大家是否遇到过这种情况，如有遇到过的烦请帮忙解答，谢谢

**Comment by EastblueOkay** [comment]
你好，详情是通过展开行显示的么？ 是否可以提供codesandbox示例呢😁

**Comment by pengzhifang** [comment]
没有通过展开行显示，只是一个详情按钮，点击后会出现详情弹窗，下边是我的截图，代码示例的话不太好弄
![image](https://user-images.githubusercontent.com/37998976/101116496-31f62380-3620-11eb-8a6f-26b8631c3043.png)

**Comment by lsky-walt** [comment]
@pengzhifang Hello，能提供一下Shineout的版本号不？还有，请问你们`Table`的`height`属性是怎么设定的？如果可以的话  能否给个复现的sandbox，这样我们会比较好查找问题所在。

**Comment by pengzhifang** [comment]
hello， 版本号是1.6.1，  hieght : "calc(100vh - 330px)",  sandBox 的话我不太会弄，而且代码也不好弄出来，还有一个现象就是，如果我加载完之后先把滚轮从上到下滚动一遍之后再在任意位置点击都不会出现这个问题，查看样式，好像是滚动区域的位置变了

**Comment by leehaoChen** [comment]
可以升级到新版本来解决改问题
