### ISSUE TITLE
The component page datepicker example, has  error in day numbers.

### ISSUE THREAD

**Issue by 51tharea** [sheinsight/shineout#922]
Hey mate.Good day for you.
I was found small issue and attached for you the report. 

![image](https://user-images.githubusercontent.com/644199/102581839-68e53280-4112-11eb-9eca-c7d39bf051b5.png)

**Comment by EastblueOkay** [comment]
@51tharea  Mate, we're starting to notice this problem.
Can I ask you if this is always a problem for you? Or is there a particular pattern?

**Comment by 51tharea** [comment]
Hey mate,  this situation does not always a problem. I just want to report.  
What do you mean by a particular pattern?

**Comment by EastblueOkay** [comment]
@51tharea We are looking for patterns in the emergence of the problem, it's a terrible problem 😿

**Comment by EastblueOkay** [comment]
#947 Mate, we've identified and solved this problem.
It was specifically caused by the incorrect use of `toLocalDateString`.
