### ISSUE TITLE
更新代码运行，怎么报错

### ISSUE THREAD

**Issue by luchaoqun125** [sheinsight/shineout#95]
![image](https://user-images.githubusercontent.com/19883840/54733935-78e77f80-4bd7-11e9-9516-1258894e995d.png)

**Comment by Lobos** [comment]
更新代码以后有没有更新npm包？

**Comment by luchaoqun125** [comment]
使用cnpm安装可以了

**Comment by Lobos** [comment]
呃，用yarn吧
