### ISSUE TITLE
动态样式很赞

### ISSUE THREAD

**Issue by Tiger-zhou** [sheinsight/shineout#974]
在公众号看到这个组件库，还挺精致的。动态样式很适合我的需求，请问有长期维护计划吗？🤩

**Comment by EastblueOkay** [comment]
@Tiger-zhou Tiger你好，感谢你对 Shineout 的评价。
Shineout 是 SHEIN 开源的桌面端 React 组件库，努力追求高效和兼容。
Shineout 目前已服务于公司内部和社区约有数百个项目，维护团队稳定，欢迎提出宝贵意见😇
